### ISSUE TITLE
Render a locar Image

### ISSUE THREAD

**Issue by maoapp** [kaddyadriano/react-native-imageedit#3]
This library is awesome but I was not able to render a local image :(, it's that possible?

**Comment by kaddyadriano** [comment]
The library only supports absolute paths right now. Will be added in the next release. 
In the mean time try to render local image like this:

```javascript
import resolveAssetSource from "react-native/Libraries/Image/resolveAssetSource";
//...
let image = resolveAssetSource(require("../path/to/image.png"));
<ImageEdit image={image} />
```
Let me know if this works for you.
